topics:
  - /scan
  - /stereo/left/image_rect
  - /stereo/left/camera_info
  - /stereo/right/image_rect
  - /stereo/right/camera_info
  - /camera/depth/image_rect_raw
  - /camera/depth/camera_info
  - /imu/data_raw
  - /tf
  - /tf_static
  - /cmd/vesc
  - /motor_state
  - /odom
  - /diagnostics
  - /rosout
